name: Test

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3

      - name: Install Python Dependencies
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.0
        with:
          python_version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: poetry run pytest --junitxml=junit/test-results.xml tests/

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}  # Use always() to always run this step to publish test results when there are test failures
        with:
          name: checks
          path: |
            junit/test-results.xml
            .coverage
